version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./themes:/var/www/html/wp-content/themes
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    depends_on:
      - db

  sftp:
    image: atmoz/sftp
    ports:
      - "2222:22"
    command: wordpress:wordpress_password:::wordpress
    volumes:
      - wordpress_data:/home/wordpress
      - ./themes:/home/wordpress/wp-content/themes

  node:
    image: node:latest
    working_dir: /app
    volumes:
      - ./themes/multib:/app
      - /app/node_modules
    command: tail -f /dev/null
    ports:
      - "3000:3000"

volumes:
  wordpress_data:
  db_data:
